#!/usr/bin/env python3
"""Archive dated ESPDet .espdl and promote it into camera firmware.

Run after quantize (user executes; agent does not train).

Steps:
  1) Copy src -> components/ball_detect/models/s3/archive/espdet_pico_224_224_ball_<stamp>.espdl
  2) Overwrite active models/s3/espdet_pico_224_224_ball.espdl (fixed name for CMake pack)
  3) Write models/s3/MODEL_STAMP.txt
  4) Write components/ball_detect/model_stamp.h (boot log shows stamp)

Examples (repo-relative):
  py -3 camera/tools/promote_ball_model.py
  py -3 camera/tools/promote_ball_model.py --note "train-2 mAP50=0.943"
  py -3 camera/tools/promote_ball_model.py --src camera/tools/esp-detection/espdet_pico_224_224_ball.espdl
"""

from __future__ import annotations

import argparse
import shutil
import sys
from datetime import datetime
from pathlib import Path

ACTIVE_NAME = "espdet_pico_224_224_ball.espdl"


def _paths(script: Path) -> tuple[Path, Path, Path, Path]:
    # camera/tools/promote_ball_model.py -> camera/
    camera_root = script.parent.parent
    espdet_root = camera_root / "tools" / "esp-detection"
    models_s3 = camera_root / "components" / "ball_detect" / "models" / "s3"
    stamp_h = camera_root / "components" / "ball_detect" / "model_stamp.h"
    return camera_root, espdet_root, models_s3, stamp_h


def _write_stamp_header(path: Path, stamp: str, note: str, archived: str) -> None:
    note_c = note.replace("\\", "\\\\").replace('"', '\\"')
    archived_c = archived.replace("\\", "\\\\").replace('"', '\\"')
    path.write_text(
        "/* Auto-generated by promote_ball_model.py — do not edit by hand. */\n"
        "#pragma once\n"
        "\n"
        f'#define BALL_DETECT_MODEL_STAMP "{stamp}"\n'
        f'#define BALL_DETECT_MODEL_NOTE "{note_c}"\n'
        f'#define BALL_DETECT_MODEL_ARCHIVE "{archived_c}"\n',
        encoding="utf-8",
        newline="\n",
    )


def main() -> int:
    script = Path(__file__).resolve()
    _camera_root, espdet_root, models_s3, stamp_h = _paths(script)

    parser = argparse.ArgumentParser(description="Promote dated ball .espdl into camera firmware")
    parser.add_argument(
        "--src",
        type=Path,
        default=espdet_root / ACTIVE_NAME,
        help=f"quantized espdl (default: esp-detection/{ACTIVE_NAME})",
    )
    parser.add_argument(
        "--stamp",
        default="",
        help="override stamp YYYYMMDD_HHMMSS (default: local now)",
    )
    parser.add_argument(
        "--note",
        default="",
        help='optional note, e.g. "train-2 mAP50=0.943"',
    )
    args = parser.parse_args()

    src = args.src.expanduser().resolve()
    if not src.is_file():
        print(f"ERROR: source not found: {src}", file=sys.stderr)
        return 1

    stamp = args.stamp.strip() or datetime.now().strftime("%Y%m%d_%H%M%S")
    if len(stamp) < 8:
        print("ERROR: --stamp too short (expect YYYYMMDD or YYYYMMDD_HHMMSS)", file=sys.stderr)
        return 1

    archive_dir = models_s3 / "archive"
    archive_dir.mkdir(parents=True, exist_ok=True)
    archived_name = f"espdet_pico_224_224_ball_{stamp}.espdl"
    archived_path = archive_dir / archived_name
    active_path = models_s3 / ACTIVE_NAME

    shutil.copy2(src, archived_path)
    shutil.copy2(src, active_path)

    note = args.note.strip() or f"promoted from {src.name}"
    (models_s3 / "MODEL_STAMP.txt").write_text(
        f"stamp={stamp}\n"
        f"active={ACTIVE_NAME}\n"
        f"archive={archived_name}\n"
        f"source={src}\n"
        f"note={note}\n"
        f"size_bytes={active_path.stat().st_size}\n",
        encoding="utf-8",
        newline="\n",
    )
    _write_stamp_header(stamp_h, stamp, note, archived_name)

    print("OK promote ball model")
    print(f"  stamp:   {stamp}")
    print(f"  archive: {archived_path}")
    print(f"  active:  {active_path}")
    print(f"  header:  {stamp_h}")
    print(f"  note:    {note}")
    print("")
    print("Next (repo root):")
    print("  idf -Project camera build")
    print("  idf -Project camera -p COMxx flash monitor")
    print('Expect boot: cam_model init ok (espdet ball stamp=... note=...)')
    return 0


if __name__ == "__main__":
    sys.exit(main())
