$ErrorActionPreference = "Stop"

Write-Host "Checking ESP-IDF environment..."

$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))

$gitCmd = Get-Command git -ErrorAction SilentlyContinue
if ($null -ne $gitCmd) {
    Write-Host "Initializing git submodules (cbb)..."
    Push-Location $repoRoot
    try {
        & git submodule update --init --recursive
        if ($LASTEXITCODE -ne 0) {
            Write-Error "Failed to initialize git submodules."
        }
    } finally {
        Pop-Location
    }
} else {
    Write-Warning "Git not found; skip submodule init. Run 'git submodule update --init --recursive' manually."
}

$espRoot = Join-Path $repoRoot "Espressif"
$frameworkRoot = Join-Path $espRoot "frameworks"
$idfVersion = "v5.5.4"
$idfPath = Join-Path $PSScriptRoot "..\Espressif\frameworks\esp-idf-v5.5.4"
$idfPath = [System.IO.Path]::GetFullPath($idfPath)

if (-not (Test-Path $idfPath)) {
    Write-Host "ESP-IDF not found. Bootstrapping a fresh local install..."

    $gitCmd = Get-Command git -ErrorAction SilentlyContinue
    if ($null -eq $gitCmd) {
        Write-Error "Git is required for zero-install flow. Please install Git for Windows first."
    }

    if (-not (Test-Path $frameworkRoot)) {
        New-Item -ItemType Directory -Path $frameworkRoot -Force | Out-Null
    }

    Write-Host "Cloning ESP-IDF $idfVersion..."
    & git clone --branch $idfVersion --depth 1 https://github.com/espressif/esp-idf.git $idfPath
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Failed to clone ESP-IDF repository."
    }
}

$installScript = Join-Path $idfPath "install.bat"
$exportScript = Join-Path $idfPath "export.bat"

if (-not (Test-Path $installScript)) {
    Write-Error "install.bat not found at: $installScript"
}

if (-not (Test-Path $exportScript)) {
    Write-Error "export.bat not found at: $exportScript"
}

Write-Host "Installing/refreshing toolchain (safe to run multiple times)..."
$env:IDF_TOOLS_PATH = $espRoot
$env:IDF_GITHUB_ASSETS = "dl.espressif.cn/github_assets"
& cmd /c "`"$installScript`" esp32s3"
if ($LASTEXITCODE -ne 0) {
    Write-Warning "ESP-IDF install.bat failed with exit code $LASTEXITCODE (GitHub/network). Retrying python env only..."
    $venvPy = Join-Path $espRoot "python_env\idf5.5_py3.13_env\Scripts\python.exe"
    if (-not (Test-Path $venvPy)) {
        $req = Join-Path $idfPath "tools\requirements\requirements.core.txt"
        $constraint = Join-Path $espRoot "espidf.constraints.v5.5.txt"
        $venvDir = Join-Path $espRoot "python_env\idf5.5_py3.13_env"
        python -m venv $venvDir
        $py = Join-Path $venvDir "Scripts\python.exe"
        & $py -m pip install -r $req --upgrade --constraint $constraint --extra-index-url https://dl.espressif.com/pypi
        Set-Content -Path (Join-Path $venvDir "idf_version.txt") -Value "5.5" -Encoding ASCII -NoNewline
    }
}

$idfCmdInit = Join-Path $espRoot "idf_cmd_init.bat"
$idfCmdInitContent = @"
@echo off
REM Local ESP-IDF environment init for VS Code / Cursor integrated terminal.
REM Regenerated by scripts\setup_env.ps1 — do not commit (Espressif/ is gitignored).
set "IDF_TOOLS_PATH=%~dp0"
if "%IDF_TOOLS_PATH:~-1%"=="\" set "IDF_TOOLS_PATH=%IDF_TOOLS_PATH:~0,-1%"
set "IDF_GITHUB_ASSETS=dl.espressif.cn/github_assets"
call "%~dp0frameworks\esp-idf-v5.5.4\export.bat"
"@
Set-Content -Path $idfCmdInit -Value $idfCmdInitContent -Encoding ASCII
Write-Host "Wrote terminal init script: $idfCmdInit"

Write-Host ""
Write-Host "Environment setup complete."
Write-Host "Run these commands in a new terminal:"
Write-Host "  cmd /k `"$exportScript`""
Write-Host "Then build:"
Write-Host "  (from repo root) idf.py -C project build"
Write-Host "  (from .\\project) idf.py build"
