/* Auto-generated by promote_ball_model.py — do not edit by hand. */
#pragma once

#define BALL_DETECT_MODEL_STAMP "20260730_180604"
#define BALL_DETECT_MODEL_NOTE "train-5 mAP50=0.961"
#define BALL_DETECT_MODEL_ARCHIVE "espdet_pico_224_224_ball_20260730_180604.espdl"
