/* Auto-generated by promote_ball_model.py — do not edit by hand. */
#pragma once

#define BALL_DETECT_MODEL_STAMP "unknown"
#define BALL_DETECT_MODEL_NOTE "run promote_ball_model.py after quantize"
#define BALL_DETECT_MODEL_ARCHIVE ""
